### ISSUE TITLE
Parallelize block processing

### ISSUE THREAD

**Issue by gakonst** [flashbots/mev-inspect-rs#24]
Currently we process each block's transactions by joining all the futures together. It'd be nice if we could also do block processing in [parallel](https://github.com/flashbots/mev-inspect-rs/blob/master/src/main.rs#L149). A naive way to do this is by spawning multiple processes of the binary. This might be an issue if we end up getting too many handles to PostGres?

**Comment by brockelmore** [comment]
might i suggest maybe looking into actix/actor model? actix in particular makes it super easy to spin up concurrent processing actors. if you're interested, i can help out - i've used actix a lot. multiple binaries seems less than optimal

**Comment by gakonst** [comment]
Not opposed, by all means!

**Comment by mattsse** [comment]
Hey, I found this to be an interesting problem and attempted a solution in #51 
However due to lack of access to an archive node I'm not sure how to test it yet

**Comment by obadiaa** [comment]
Thank you @mattsse !!
