### ISSUE TITLE
Tokio-Tungstenite missing branch

### ISSUE THREAD

**Issue by brockelmore** [flashbots/mev-inspect-rs#32]
**Version**
Fresh `git clone` of master branch.

**Platform**
Linux main 5.9.14-arch1-1

**Description**

```tokio-tungstenite = { git = "https://github.com/dnaka91/tokio-tungstenite", branch = "tokio-1.0" }```

This branch no longer exists so `cargo build` no longer works. Not sure what this was patching.

**Comment by gakonst** [comment]
Should be fixed in https://github.com/flashbots/mev-inspect-rs/commit/ee8de61316d4e15675fec9ebac4f6b79e2f658dd.
