### ISSUE TITLE
Add Uniswap ETH block price oracle

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-inspect-rs#37]
Could we add logging of Ethereum price from Uniswap oracle in our db as an 11th column?

It should be a simple inspector in Rust afaik and would help us for our USD conversions (so that we convert ETH to USD based on Uniswap oracle ETH block price instead of the daily price we're using atm)

Ideally starting from Jan 1 2021, before we can use Will's db of ETH prices per minute for 2020

**Comment by obadiaa** [comment]
@epheph iz done right?

**Comment by epheph** [comment]
It is a side-loaded thing via typescript, but ya, it's done. need to push it out but it's running.

**Comment by obadiaa** [comment]
Closing this issue, thank you @epheph!
