### ISSUE TITLE
Run inspectors in the following block/date intervals currently missing

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-inspect-rs#42]
- Starting at January 1st 2020: Inspectors currently starting at block 9,200,000 which is Jan 2, want them to start at Jan 1 so block 9193266

Data seems to be missing from the following date ranges:
- November 27th 2020 to February 4th 2021
- November 12 to November 17 2020
- November 3 to November 10th 2020
- October 22 2020 to October 27 2020
- some interval between 10,530,000 and 10,550,000 (~late July)

**Comment by gakonst** [comment]
January has been filled, started filling from Oct 22.

**Comment by gakonst** [comment]
Closing this, as I'd expect this to no longer happen since we merged #51

**Comment by obadiaa** [comment]
Amazing! Curious if the problem will be fully solved but thanks @mattsse :)
